### ISSUE TITLE
Fused with which  Amazon view dataset  should be download

### ISSUE THREAD

**Issue by CreaterLL** [Chain123/RecGURU#1]
Hello, I,m not clear which  Amazon view dataset  should be download from :https://nijianmo.github.io/amazon/index.html ,there are any clues?
Also, is it convenient to provide the environmental configuration of the project?

**Comment by Chain123** [comment]
Hi， 

Just download the dataset you want to use, e.g. ‘reviews, '5-core', and 'rating'. 
![企业微信截图_16388442971876](https://user-images.githubusercontent.com/28283815/144955456-171d2a05-f393-4723-aff0-e331741030a1.png)

For the environment, I am running with Pytorch 1.1 with python=3.6. If there are other packages missing, simply run conda install xx, or pip install xxx.

**Comment by CreaterLL** [comment]
Uh,but i want to know which datasets should i download if i will reproduce the result in the paper.

**Comment by Chain123** [comment]
In the paper, we are using 
![企业微信截图_16388507321408](https://user-images.githubusercontent.com/28283815/144965529-f70f2411-332b-418d-9802-5e2257c90ab8.png)
which are the "Books", "Sports and Outdoors", "Movies and TV", and ''Clothing Shoes and Jewelry''.

**Comment by CreaterLL** [comment]
Okey, thank you  very much!
