### ISSUE TITLE
Confused with the result_a.*  file

### ISSUE THREAD

**Issue by CreaterLL** [Chain123/RecGURU#2]
hi，after running  ‘python train_gan.py --cross "True"’，i got only result_a.* files  and the content is like as 
![image](https://user-images.githubusercontent.com/63894612/147454473-28cd0d41-423c-4cfe-b927-1a6d0db8a0af.png) 、
![image](https://user-images.githubusercontent.com/63894612/147455319-4e28fdef-c1f6-4ca9-a010-d0392674d786.png)
,i'm so confused with them. and i haven't found the HR@*metrics. 
could you please give me some instructions? 
besides,i 'm also confused with if there are both results of two domains in the result_a.* files？
Thank you!

**Comment by Chain123** [comment]
The numbers, i.e. 5, 10, 20 represent the K value for metrics such as HT@K, NDCG@K, etc. It is defined in the evaluation_2 method (line 90 of gan_training.py), please go to the function for details.
