### ISSUE TITLE
请问collected_data如何处理？

### ISSUE THREAD

**Issue by caojiangxia** [Chain123/RecGURU#3]
Hi, Li:

我在下载完collected_data.gz之后，解压得到collected_data，但是这似乎无法打开得到相应的train/valid/test。

另外business_process.py似乎也不能直接处理collected_data.gz这个文件。

请问应该如何得到处理后的数据呢？

**Comment by Chain123** [comment]
Hi Caojiang, 

collected_data里面应该是19个.gz文件，名字类似00000x_0.gz，这些是原始数据。 business_process.py可以直接处理这些文件，它是根据提前定义的用户重合度（overlap_ratio）进一步得到不同重合度的跨域情况。business_process.py里面有几个路劲需要自己修改一下。

**Comment by caojiangxia** [comment]
诶，不过我解压后的collected_data打不开呢，没看到00000x_0.gz这几个文件。

**Comment by Chain123** [comment]
再一次解压collected_data，得到一个kdd的文件夹，里面就是.gz数据

**Comment by caojiangxia** [comment]
你好，再解压一次用什么命令呀。我试了unzip和gzip都不行。

**Comment by Chain123** [comment]
I used 7z on windows (not in terminal). For your convenience, I've uploaded a new version: https://drive.google.com/file/d/1Eszu-mApyzvVj6tAunPuYql6aIJlQmhg/view?usp=sharing which is named kdd.tar.gz. Just use: "tar -xzvf kdd.tar.gz" to unzip it in a terminal (mac, Linux, or windows).

**Comment by caojiangxia** [comment]
Thank you!

**Comment by caojiangxia** [comment]
这个链接的权限好像还需要修改一下。

**Comment by Chain123** [comment]
oh, I see, 我之后修改一下readme中的链接，现在这个链接你应该可以用了。
