### ISSUE TITLE
business_process.py 文件没有生成kdd_10_f  只有kdd_10 

### ISSUE THREAD

**Issue by CreaterLL** [Chain123/RecGURU#5]
![image](https://user-images.githubusercontent.com/63894612/161387541-9ac52b9d-37d4-452e-90a7-406b4eb880e8.png)
business_process.py文件只生成了kdd_10文件 ，为什么会显示kdd_10_f文件找不到呢   我需要将kdd_10_f直接改成kdd_10吗

另外  代码中需要freq的文件  但是business_process.py并没有在kdd_10中文件夹中生成freq文件，请问这里的freq文件是需要自己生成吗？

**Comment by Chain123** [comment]
是的，这个数据的路劲是你自己生成的自己电脑本地的数据路劲，你现在这个路劲是我运行代码的路劲，你要在config_auto4rec.py 文件中修改这些configuration。

**Comment by CreaterLL** [comment]
谢谢您！
